#!/usr/bin/env php
<?php
/*
|--------------------------------------------------------------------------
| Override the INI settings.
|--------------------------------------------------------------------------
|
| Set come default INI settings just in case.
|
*/
set_time_limit(0);
ini_set("log_errors",           1);
ini_set("error_log",            __DIR__.DIRECTORY_SEPARATOR."app".DIRECTORY_SEPARATOR."error.log");
ini_set("memory_limit",         "-1");

/*
|--------------------------------------------------------------------------
| Require the autoloader
|--------------------------------------------------------------------------
|
| Require in autoloader for all vendor and source files.
| Composer is awesome. Seriously.
|
*/
require_once 'vendor/autoload.php';
require_once __DIR__.DIRECTORY_SEPARATOR."app".DIRECTORY_SEPARATOR."functions.php";
/*
|--------------------------------------------------------------------------
| Define default paths
|--------------------------------------------------------------------------
|
| Set default paths for Application.
|
*/
define("ROOT_DIR",             __DIR__      .DIRECTORY_SEPARATOR);
define("APP_DIR",               ROOT_DIR    ."app".DIRECTORY_SEPARATOR);
define("REPORTS_DIR",           APP_DIR     ."reports".DIRECTORY_SEPARATOR);

define("CONFIG_FILE",           APP_DIR     ."config.php");
define("EVENT_LOG",             APP_DIR     ."event.log");
define("ERROR_LOG",             APP_DIR     ."error.log");

/*
|--------------------------------------------------------------------------
| Instantiate Feather
|--------------------------------------------------------------------------
|
| Bootstrap the toolkit.
|
*/
$app = new \App\Feather();
$app->run();